version: "3.9"
services:
  ui:
    container_name: indefinite_studies_web_ui
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      APP_PORT: "${APP_PORT}"
networks:
  default:
    external: true
    name: indefinite-studies-environment
