version: "3.9"
services:
  ui:
    container_name: indefinite_studies_web_ui
    build: .
    ports:
      - "3000:3000"
networks:
  default:
    external: true
    name: indefinite-studies-environment